export function UserException(message) {
  this.message = message;
  this.name = 'Исключение, определенное пользователем';
}
